public class FridgeInfo
{
	public static void main(String[] args)
	{
       Fridge fridge=new Fridge();
       fridge.brand="LG";
       fridge.price=28000;
       fridge.model="GL-T292R";
       fridge.capacity="260L";
       fridge.type="Double Door";
       fridge.display();
       fridge.isOn();
       fridge.isOff();
       fridge.temperature();
       System.out.println("**********************************");
       Fridge fridge1=new Fridge();
       fridge1.brand="Samsung";
       fridge1.price=25000;
       fridge1.model="RT28T";
       fridge1.capacity="253L";
       fridge1.type="Top Freezer";
       fridge1.display();
       fridge1.isOn();
       fridge1.isOff();
       fridge1.temperature();
       System.out.println("**********************************");
       Fridge fridge2=new Fridge();
       fridge2.brand="Whirpool";
       fridge2.price=30000;
       fridge2.model="WRF553";
       fridge2.capacity="250L";
       fridge2.type="Double Door";
       fridge2.display();
       fridge2.isOn();
       fridge2.isOff();
       fridge2.temperature();
       System.out.println("**********************************");
       Fridge fridge3=new Fridge();
       fridge3.brand="Godrej";
       fridge3.price=20000;
       fridge3.model="RD Edge 205";
       fridge3.capacity="190L";
       fridge3.type="Double Door";
       fridge3.display();
       fridge3.isOn();
       fridge3.isOff();
       fridge3.temperature();
       System.out.println("**********************************");
       Fridge fridge4=new Fridge();
       fridge4.brand="Haier";
       fridge4.price=19500;
       fridge4.model="HRD 1953";
       fridge4.capacity="195L";
       fridge4.type="Single Door";
       fridge4.display();
       fridge4.isOn();
       fridge4.isOff();
       fridge4.temperature();
       System.out.println("**********************************");
       Fridge fridge5=new Fridge();
       fridge5.brand="Bosch";
       fridge5.price=45000;
       fridge5.model="KDN30VB";
       fridge5.capacity="292L";
       fridge5.type="Bottom Freezer";
       fridge5.display();
       fridge5.isOn();
       fridge5.isOff();
       fridge5.temperature();
       System.out.println("**********************************");
       Fridge fridge6=new Fridge();
       fridge6.brand="Panasonic";
       fridge6.price=35000;
       fridge6.model="NR-BG311";
       fridge6.capacity="260L";
       fridge6.type="Double Door";
       fridge6.display();
       fridge6.isOn();
       fridge6.isOff();
       fridge6.temperature();
       System.out.println("**********************************");
       Fridge fridge7=new Fridge();
       fridge7.brand="EHE5220";
       fridge7.price=38000;
       fridge7.model="Electrolux";
       fridge7.capacity="270L";
       fridge7.type="Double Door";
       fridge7.display();
       fridge7.isOn();
       fridge7.isOff();
       fridge7.temperature();
       System.out.println("**********************************");
       Fridge fridge8=new Fridge();
       fridge8.brand="3Star";
       fridge8.price=18000;
       fridge8.model="Voltas";
       fridge8.capacity="185L";
       fridge8.type="Single Door";
       fridge8.display();
       fridge8.isOn();
       fridge8.isOff();
       fridge8.temperature();
       System.out.println("**********************************");
       Fridge fridge9=new Fridge();
       fridge9.brand="GLS292";
       fridge9.price=32000;
       fridge9.model="LG";
       fridge9.capacity="260L";
       fridge9.type="Double Door";
       fridge9.display();
       fridge9.isOn();
       fridge9.isOff();
       fridge9.temperature();
       

	}
}